version: '2.7'

services:
  db:
    image: bitnami/postgresql:14
    environment:
      POSTGRESQL_USERNAME: '${DB_USERNAME}'
      POSTGRESQL_PASSWORD: '${DB_PASSWORD}'
      POSTGRESQL_DATABASE: '${DB_DATABASE}'
    ports:
      - '${DB_PORT}:5432'
    networks:
      - db_network

  redis:
    image: redis:alpine3.16
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - db_network

networks:
  db_network: { driver: bridge }
